// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sloos.Pump.EntityFramework
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Mapping : MappingBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 2 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"

// Simplifying assumptions based on reverse engineer rules
//  - No complex types
//  - One entity container
//  - No inheritance
//  - Always have two navigation properties
//  - All associations expose FKs (except many:many)

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 13 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 15 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ConceptualMappingName));
            
            #line default
            #line hidden
            this.Write(" : global::System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<");
            
            #line 15 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ConceptualName));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public ");
            
            #line 17 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ConceptualMappingName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            // Primary Key\r\n            ");
            
            #line 20 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MappingKeyView.AsStatement()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n            // Properties\r\n");
            
            #line 23 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"

			foreach (var mappingPropertyView in this.MappingPropertyViews) {
				if (mappingPropertyView.Attributes.Count == 0) {
					continue;
				}

            
            #line default
            #line hidden
            this.Write("            this.Property(x => x.");
            
            #line 29 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappingPropertyView.ConceptualName));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 30 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"

				foreach (var attribute in mappingPropertyView.Attributes) {

            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 33 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute));
            
            #line default
            #line hidden
            
            #line 33 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
 if (attribute == mappingPropertyView.Attributes[mappingPropertyView.Attributes.Count - 1]) 
            
            #line default
            #line hidden
            
            #line 33 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(";"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 34 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
			
				}

            
            #line default
            #line hidden
            
            #line 37 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
			
			}

            
            #line default
            #line hidden
            this.Write("\r\n            // Table & Column Mappings\r\n            this.ToTable(\"");
            
            #line 42 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.StoreName));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 42 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SchemaName));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 43 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"

			foreach (var mappingPropertyView in this.MappingPropertyViews) {

            
            #line default
            #line hidden
            this.Write("            this.Property(x => x.");
            
            #line 46 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappingPropertyView.ConceptualName));
            
            #line default
            #line hidden
            this.Write(").HasColumnName(\"");
            
            #line 46 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappingPropertyView.ConceptualName));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 47 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
			
			}

            
            #line default
            #line hidden
            this.Write("\r\n            // Relationships\r\n");
            
            #line 52 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"

            // Many-to-Many
			foreach (var mappingManyToManyView in this.MappingManyToManyViews) {

            
            #line default
            #line hidden
            this.Write("            this.HasMany(x => x.");
            
            #line 56 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappingManyToManyView.HasMany));
            
            #line default
            #line hidden
            this.Write(")\r\n                .WithMany(x => x.");
            
            #line 57 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappingManyToManyView.WithMany));
            
            #line default
            #line hidden
            this.Write(")\r\n                .Map(x =>\r\n                    {\r\n                        x.To" +
                    "Table(\"");
            
            #line 60 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappingManyToManyView.MappingTableName));
            
            #line default
            #line hidden
            this.Write("\");\r\n                        x.MapLeftKey(\"");
            
            #line 61 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappingManyToManyView.MapLeftKeys[0]));
            
            #line default
            #line hidden
            this.Write("\");\r\n                        x.MapRightKey(\"");
            
            #line 62 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappingManyToManyView.MapRightKeys[0]));
            
            #line default
            #line hidden
            this.Write("\");\r\n                    });\r\n");
            
            #line 64 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
			
			}

            
            #line default
            #line hidden
            
            #line 67 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"

			// One-to-Many
            foreach (var mappingRelationshipForeignKeyView in this.MappingRelationshipForeignKeyViews) {

            
            #line default
            #line hidden
            this.Write("            this.");
            
            #line 71 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappingRelationshipForeignKeyView.EntityNecessity));
            
            #line default
            #line hidden
            this.Write("(x => x.");
            
            #line 71 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mappingRelationshipForeignKeyView.EntityName));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 72 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"

				foreach (var attribute in mappingRelationshipForeignKeyView.Attributes) {

            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 75 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute));
            
            #line default
            #line hidden
            
            #line 75 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
 if (attribute == mappingRelationshipForeignKeyView.Attributes[mappingRelationshipForeignKeyView.Attributes.Count - 1]) 
            
            #line default
            #line hidden
            
            #line 75 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(";"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 76 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
			
				}

            
            #line default
            #line hidden
            
            #line 79 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"
			
			}

            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 85 "C:\dev.my\sloos.git\src\Sloos.Pump\EntityFramework\Mapping.tt"

	public global::Sloos.Pump.TextTemplate.MappingFactory Factory { get; set; }

	public string StoreName { get { return this.Factory.StoreName; } }
	public string ConceptualMappingName { get { return this.Factory.ConceptualMappingName; } }
	public string ConceptualName { get { return this.Factory.ConceptualName; } }
	public string SchemaName { get { return this.Factory.SchemaName; } }
	public string Namespace { get { return this.Factory.Namespace; } }

    public global::Sloos.Pump.EntityFramework.MappingKeyView MappingKeyView { get { return this.Factory.MappingKeyView; } }
    public global::Sloos.Pump.EntityFramework.MappingPropertyView[] MappingPropertyViews { get { return this.Factory.MappingPropertyViews; } }
    public global::Sloos.Pump.EntityFramework.MappingRelationshipForeignKeyView[] MappingRelationshipForeignKeyViews { get { return this.Factory.MappingRelationshipForeignKeyViews; } }
    public global::Sloos.Pump.EntityFramework.MappingManyToManyView[] MappingManyToManyViews { get { return this.Factory.MappingManyToManyViews; } }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class MappingBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
