//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace Sloos.Pump.SsdlSchema.Xsd {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    [XmlRoot("Schema", Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl", IsNullable=false)]
    public partial class TSchema {
        
        private TAssociation[] associationField;
        
        private TEntityType[] entityTypeField;
        
        private EntityContainer[] entityContainerField;
        
        private TFunction[] functionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string namespaceField;
        
        private string aliasField;
        
        private string providerField;
        
        private string providerManifestTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [XmlElement("Association")]
        public TAssociation[] Association {
            get {
                return this.associationField;
            }
            set {
                this.associationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("EntityType")]
        public TEntityType[] EntityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("EntityContainer")]
        public EntityContainer[] EntityContainer {
            get {
                return this.entityContainerField;
            }
            set {
                this.entityContainerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("Function")]
        public TFunction[] Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string ProviderManifestToken {
            get {
                return this.providerManifestTokenField;
            }
            set {
                this.providerManifestTokenField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TAssociation {
        
        private TDocumentation documentationField;
        
        private TAssociationEnd[] endField;
        
        private TConstraint referentialConstraintField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("End")]
        public TAssociationEnd[] End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        public TConstraint ReferentialConstraint {
            get {
                return this.referentialConstraintField;
            }
            set {
                this.referentialConstraintField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TDocumentation {
        
        private System.Xml.XmlElement summaryField;
        
        private System.Xml.XmlElement longDescriptionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [XmlAnyElement(Name="Summary", Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
        public System.Xml.XmlElement Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement(Name="LongDescription", Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
        public System.Xml.XmlElement LongDescription {
            get {
                return this.longDescriptionField;
            }
            set {
                this.longDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TRowType {
        
        private TProperty[] itemsField;
        
        /// <remarks/>
        [XmlElement("Property")]
        public TProperty[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TProperty {
        
        private TDocumentation documentationField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string typeField;
        
        private bool nullableField;
        
        private string defaultValueField;
        
        private string maxLengthField;
        
        private bool fixedLengthField;
        
        private bool fixedLengthFieldSpecified;
        
        private string precisionField;
        
        private string scaleField;
        
        private bool unicodeField;
        
        private bool unicodeFieldSpecified;
        
        private string collationField;
        
        private string sRIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public TProperty() {
            this.nullableField = true;
        }
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Nullable {
            get {
                return this.nullableField;
            }
            set {
                this.nullableField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string MaxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool FixedLength {
            get {
                return this.fixedLengthField;
            }
            set {
                this.fixedLengthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool FixedLengthSpecified {
            get {
                return this.fixedLengthFieldSpecified;
            }
            set {
                this.fixedLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string Precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string Scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool Unicode {
            get {
                return this.unicodeField;
            }
            set {
                this.unicodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool UnicodeSpecified {
            get {
                return this.unicodeFieldSpecified;
            }
            set {
                this.unicodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Collation {
            get {
                return this.collationField;
            }
            set {
                this.collationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string SRID {
            get {
                return this.sRIDField;
            }
            set {
                this.sRIDField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TCollectionType {
        
        private TRowType itemField;
        
        /// <remarks/>
        [XmlElement("RowType")]
        public TRowType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TFunctionReturnType {
        
        private TCollectionType itemField;
        
        /// <remarks/>
        [XmlElement("CollectionType")]
        public TCollectionType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TParameter {
        
        private TDocumentation documentationField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string typeField;
        
        private TParameterMode modeField;
        
        private bool modeFieldSpecified;
        
        private string maxLengthField;
        
        private string precisionField;
        
        private string scaleField;
        
        private string sRIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public TParameterMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ModeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string MaxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string Precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string Scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string SRID {
            get {
                return this.sRIDField;
            }
            set {
                this.sRIDField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public enum TParameterMode {
        
        /// <remarks/>
        In,
        
        /// <remarks/>
        Out,
        
        /// <remarks/>
        InOut,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TFunction {
        
        private TDocumentation documentationField;
        
        private object[] itemsField;
        
        private string nameField;
        
        private string returnTypeField;
        
        private bool aggregateField;
        
        private bool aggregateFieldSpecified;
        
        private bool builtInField;
        
        private bool builtInFieldSpecified;
        
        private string storeFunctionNameField;
        
        private bool niladicFunctionField;
        
        private bool niladicFunctionFieldSpecified;
        
        private bool isComposableField;
        
        private TParameterTypeSemantics parameterTypeSemanticsField;
        
        private string schemaField;
        
        private string schema1Field;
        
        private string name1Field;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public TFunction() {
            this.isComposableField = true;
            this.parameterTypeSemanticsField = TParameterTypeSemantics.AllowImplicitConversion;
        }
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        [XmlElement("CommandText", typeof(string))]
        [XmlElement("Parameter", typeof(TParameter))]
        [XmlElement("ReturnType", typeof(TFunctionReturnType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string ReturnType {
            get {
                return this.returnTypeField;
            }
            set {
                this.returnTypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool Aggregate {
            get {
                return this.aggregateField;
            }
            set {
                this.aggregateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool AggregateSpecified {
            get {
                return this.aggregateFieldSpecified;
            }
            set {
                this.aggregateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool BuiltIn {
            get {
                return this.builtInField;
            }
            set {
                this.builtInField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool BuiltInSpecified {
            get {
                return this.builtInFieldSpecified;
            }
            set {
                this.builtInFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string StoreFunctionName {
            get {
                return this.storeFunctionNameField;
            }
            set {
                this.storeFunctionNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool NiladicFunction {
            get {
                return this.niladicFunctionField;
            }
            set {
                this.niladicFunctionField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool NiladicFunctionSpecified {
            get {
                return this.niladicFunctionFieldSpecified;
            }
            set {
                this.niladicFunctionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool IsComposable {
            get {
                return this.isComposableField;
            }
            set {
                this.isComposableField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TParameterTypeSemantics.AllowImplicitConversion)]
        public TParameterTypeSemantics ParameterTypeSemantics {
            get {
                return this.parameterTypeSemanticsField;
            }
            set {
                this.parameterTypeSemanticsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Schema {
            get {
                return this.schemaField;
            }
            set {
                this.schemaField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute("Schema", Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/ado/2007/12/edm/EntityStoreSchemaGenerator")]
        public string Schema1 {
            get {
                return this.schema1Field;
            }
            set {
                this.schema1Field = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/ado/2007/12/edm/EntityStoreSchemaGenerator")]
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public enum TParameterTypeSemantics {
        
        /// <remarks/>
        ExactMatchOnly,
        
        /// <remarks/>
        AllowImplicitPromotion,
        
        /// <remarks/>
        AllowImplicitConversion,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TEntityProperty {
        
        private TDocumentation documentationField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string typeField;
        
        private bool nullableField;
        
        private string defaultValueField;
        
        private string maxLengthField;
        
        private bool fixedLengthField;
        
        private bool fixedLengthFieldSpecified;
        
        private string precisionField;
        
        private string scaleField;
        
        private bool unicodeField;
        
        private bool unicodeFieldSpecified;
        
        private string collationField;
        
        private string sRIDField;
        
        private TStoreGeneratedPattern storeGeneratedPatternField;
        
        private bool storeGeneratedPatternFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public TEntityProperty() {
            this.nullableField = true;
        }
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Nullable {
            get {
                return this.nullableField;
            }
            set {
                this.nullableField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string MaxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool FixedLength {
            get {
                return this.fixedLengthField;
            }
            set {
                this.fixedLengthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool FixedLengthSpecified {
            get {
                return this.fixedLengthFieldSpecified;
            }
            set {
                this.fixedLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string Precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string Scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool Unicode {
            get {
                return this.unicodeField;
            }
            set {
                this.unicodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool UnicodeSpecified {
            get {
                return this.unicodeFieldSpecified;
            }
            set {
                this.unicodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Collation {
            get {
                return this.collationField;
            }
            set {
                this.collationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string SRID {
            get {
                return this.sRIDField;
            }
            set {
                this.sRIDField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public TStoreGeneratedPattern StoreGeneratedPattern {
            get {
                return this.storeGeneratedPatternField;
            }
            set {
                this.storeGeneratedPatternField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool StoreGeneratedPatternSpecified {
            get {
                return this.storeGeneratedPatternFieldSpecified;
            }
            set {
                this.storeGeneratedPatternFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public enum TStoreGeneratedPattern {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Identity,
        
        /// <remarks/>
        Computed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TEntityKeyElement {
        
        private TPropertyRef[] propertyRefField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [XmlElement("PropertyRef")]
        public TPropertyRef[] PropertyRef {
            get {
                return this.propertyRefField;
            }
            set {
                this.propertyRefField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TPropertyRef {
        
        private TDocumentation documentationField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TEntityType {
        
        private TDocumentation documentationField;
        
        private TEntityKeyElement keyField;
        
        private TEntityProperty[] itemsField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        public TEntityKeyElement Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("Property")]
        public TEntityProperty[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TReferentialConstraintRoleElement {
        
        private TDocumentation documentationField;
        
        private TPropertyRef[] propertyRefField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string roleField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("PropertyRef")]
        public TPropertyRef[] PropertyRef {
            get {
                return this.propertyRefField;
            }
            set {
                this.propertyRefField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TConstraint {
        
        private TDocumentation documentationField;
        
        private TReferentialConstraintRoleElement principalField;
        
        private TReferentialConstraintRoleElement dependentField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        public TReferentialConstraintRoleElement Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <remarks/>
        public TReferentialConstraintRoleElement Dependent {
            get {
                return this.dependentField;
            }
            set {
                this.dependentField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TOnAction {
        
        private TDocumentation documentationField;
        
        private System.Xml.XmlElement[] anyField;
        
        private TAction actionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public TAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public enum TAction {
        
        /// <remarks/>
        Cascade,
        
        /// <remarks/>
        Restrict,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class TAssociationEnd {
        
        private TDocumentation documentationField;
        
        private TOnAction[] onDeleteField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string typeField;
        
        private string roleField;
        
        private TMultiplicity multiplicityField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("OnDelete")]
        public TOnAction[] OnDelete {
            get {
                return this.onDeleteField;
            }
            set {
                this.onDeleteField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public TMultiplicity Multiplicity {
            get {
                return this.multiplicityField;
            }
            set {
                this.multiplicityField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public enum TMultiplicity {
        
        /// <remarks/>
        [XmlEnum("0..1")]
        Item01,
        
        /// <remarks/>
        [XmlEnum("1")]
        Item1,
        
        /// <remarks/>
        [XmlEnum("*")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    [XmlRoot(Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl", IsNullable=false)]
    public partial class EntityContainer {
        
        private TDocumentation documentationField;
        
        private object[] itemsField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("AssociationSet", typeof(EntityContainerAssociationSet))]
        [XmlElement("EntitySet", typeof(EntityContainerEntitySet))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class EntityContainerAssociationSet {
        
        private TDocumentation documentationField;
        
        private EntityContainerAssociationSetEnd[] endField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string associationField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("End")]
        public EntityContainerAssociationSetEnd[] End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Association {
            get {
                return this.associationField;
            }
            set {
                this.associationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class EntityContainerAssociationSetEnd {
        
        private TDocumentation documentationField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string roleField;
        
        private string entitySetField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string EntitySet {
            get {
                return this.entitySetField;
            }
            set {
                this.entitySetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm/ssdl")]
    public partial class EntityContainerEntitySet {
        
        private TDocumentation documentationField;
        
        private string definingQueryField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string entityTypeField;
        
        private string schemaField;
        
        private string tableField;
        
        private TSourceType typeField;
        
        private bool typeFieldSpecified;
        
        private string schema1Field;
        
        private string name1Field;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public TDocumentation Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        public string DefiningQuery {
            get {
                return this.definingQueryField;
            }
            set {
                this.definingQueryField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string EntityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Schema {
            get {
                return this.schemaField;
            }
            set {
                this.schemaField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/ado/2007/12/edm/EntityStoreSchemaGenerator")]
        public TSourceType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute("Schema", Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/ado/2007/12/edm/EntityStoreSchemaGenerator")]
        public string Schema1 {
            get {
                return this.schema1Field;
            }
            set {
                this.schema1Field = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/ado/2007/12/edm/EntityStoreSchemaGenerator")]
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://schemas.microsoft.com/ado/2007/12/edm/EntityStoreSchemaGenerator")]
    public enum TSourceType {
        
        /// <remarks/>
        Tables,
        
        /// <remarks/>
        Views,
    }
}
